#### build with 
#### nvidia-docker build -f /home/enginemaster/cccc-server/cutechess/build/Dockerfile-lc0-gpu -t "chess/lc0:${TAG}" .
FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04 as builder
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

WORKDIR /root
RUN apt-get update && \
    apt-get install -y \
    python3 \
    ninja-build \
    python3-pip \
    zlib1g-dev \
    ocl-icd-libopencl1 \
    wget \
    git \
    python3-venv
RUN PATH="/$HOME/.local/bin:$PATH" && \
 git clone --recurse-submodules https://github.com/LeelaChessZero/lc0.git && \
        echo hi && \
    cd lc0 && \
    git checkout $(git tag --list |tail -1) && \
    pip3 install virtualenv --user && \
    pip3 install meson --user && \
        ln -s /usr/bin/python3 /usr/bin/python && \
    INSTALL_PREFIX=/root/.local ./build.sh -Db_lto=true -Ddefault_library=static >> /root/log-`date +%s`

FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

ARG TZ='America/Los_Angeles'

WORKDIR /root

COPY --from=builder /root/lc0/build/release /root/lc0
COPY lc0gpu.sh /root

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y \
    wget \
        libgomp1 \
        libprotobuf10 \
        cuda-toolkit-11-0 && \
    apt purge wget git -y && \
    apt autoclean && chmod +x /root/lc0gpu.sh

ARG BUILD_DATE
ARG VCS_URL
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0.0"

CMD [ "/root/lc0gpu.sh" ]
