FROM debian:10-slim as builder

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root
RUN apt-get update && \
    apt-get install -y \
    python3 \
    ninja-build \
    protobuf-compiler \
    libprotobuf-dev \
    python3-pip \
    zlib1g-dev \
    ocl-icd-libopencl1 \
    tzdata \
    wget \
    git \
    python3-venv && \

    PATH="/$HOME/.local/bin:$PATH" && \
    git clone --recurse-submodules https://github.com/LeelaChessZero/lc0.git && \
    cd lc0 && \
    #git checkout $(git tag --list |grep -v rc |tail -1) && \
    #git checkout $(git tag --list |tail -1) && \
    git checkout 69105b4 && \
    pip3 install virtualenv --user && \
    pip3 install meson --user && \
        ln -s /usr/bin/python3 /usr/bin/python && \
    INSTALL_PREFIX=/root/.local ./build.sh -Db_lto=true -Ddefault_library=static >> /root/log-`date +%s`

FROM debian:10-slim

ARG TZ='America/Los_Angeles'

WORKDIR /root

COPY --from=builder /root/lc0/build/release /root/lc0
COPY lc0gpu.sh /root

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y \
    tzdata \
    wget \
    libgomp1 \
    libprotobuf17 && \
    apt purge wget git -y && \
    apt autoclean

ARG BUILD_DATE
ARG VCS_URL
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0.0"

CMD [ "/root/lc0gpu.sh" ]

