#### build with 
#### nvidia-docker build -f Dockerfile-leelenstein -t chess/leelenstein:latest . 

FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 as builder

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root
RUN apt-get update && \
    apt-get install -y \
    python3 \
    ninja-build \
    python3-pip \
    zlib1g-dev \
    tzdata \
    wget \
    git \
    python3-venv

RUN PATH="/$HOME/.local/bin:$PATH" && \
    git clone  --recurse-submodules https://github.com/jjoshua2/lc0 && \
    cd lc0 &&  \
    pip3 install virtualenv --user && \
    pip3 install meson --user && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    INSTALL_PREFIX=/root/.local ./build.sh -Db_lto=true -Dblas=false -Dopencl=false

FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
ENV DEBIAN_FRONTEND=noninteractive

ARG TZ='America/Los_Angeles'

WORKDIR /root

COPY --from=builder /root/lc0/build/release /root/lc0
COPY lc0gpu.sh /root

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y \
    tzdata \
    wget \
    libgomp1 \
    libprotobuf10 cuda-toolkit-10-2 && \
    apt purge wget git -y && \
    apt autoclean && chmod +x /root/lc0gpu.sh

ARG BUILD_DATE
ARG VCS_URL
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0.0"

CMD [ "/root/lc0gpu.sh" ]

